### ISSUE TITLE
investigate dp0.2 duplicate objects

### ISSUE THREAD

**Issue by gschwend** [linea-it/pz-compute#108]
```[tasklist]
### Tasks
- [x] create two dp0.2 subsamples (odd and even tracts) in hipscat format
- [x] x-match them
- [x] write parquet file with the result of the matching, containing only the objects with a counterpart (inner join-like)
- [x] plot their spatial distribution as a scatter plot
```

it should show points that fall exactly on the patches edges, where we had found overdensities in the whole sample: 
![Image](https://github.com/user-attachments/assets/22ec12e7-be7b-46cc-b2aa-57ef8d18a52e)
