### ISSUE TITLE
Apply dereddening to magnitudes

### ISSUE THREAD

**Issue by gschwend** [linea-it/pz-compute#35]
```[tasklist]
### Tasks
- [x] download dustmaps to lustre T1
- [x] apply (optional) reddening correction (default: SDF98 map)
- [x] reduce mags and errs to 4 decimal cases
- [x] add objectId as regular column
- [ ] update documentation
```
