### ISSUE TITLE
Adapt prepare-pz-tests to slurm 

### ISSUE THREAD

**Issue by gschwend** [linea-it/pz-compute#67]
Antigo issue #44 ressuscitado: 

O script de preparação (não confundir com pre-processing) para ser executado antes de cada processo deverá automatizar as seguintes tarefas: 

- [x] obter nome do processo e comentário da linha de comando
- [x] obter nome do usuário do sistema
- [x] criar diretório com nome do processo
- [x] criar subdiretório `input` dentro do diretório do processo 
- [x] criar arquivo `process_info.yaml` com os metadados dentro do diretório do processo 
- [x] copiar um pz-compute.yaml default 
- [x] `source ~app.photoz/conf-pz-compute-user.sh` 

O script de pós-processamento deve coletar informações nos logs do slurm e atualizar o `process_info.yaml` com: 

- [x] start time
- [x] finish time
- [x] duration 

```[tasklist]
### Tasks
```
