### ISSUE TITLE
improvements on skinny tables

### ISSUE THREAD

**Issue by gschwend** [linea-it/pz-compute#78]
```[tasklist]
### Tasks
- [x] round mags and errors to 4 decimal cases
- [ ] increase file sizes to 400k objects
- [ ] https://github.com/linea-it/pz-compute/issues/79
```
